language: ruby
before_install:
  - gem install bundler
  - gem install kramdown
  - gem install therubyracer
  - gem install jekyll
  - gem install jekyll-sitemap
script: jekyll build -d _site
rvm:
  - 2.0.0
  - 2.1.1
