# Permalinks
permalink:        pretty
# Setup
url:              http://gh.mattrude.com
# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ""
title:            Matt Rude

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  A pretentious two-column [Jekyll](http://jekyllrb.com/) theme, stolen by [`@qwtel`](https://twitter.com/qwtel)
  from [Hyde](http://hyde.getpoole.com).
  You could say it was.. [hydejacked](http://media3.giphy.com/media/makedRIckZBW8/giphy.gif).

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'
author:
  name:           'Matt Rude'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        mdrude
  github:         mattrude

  # Setting a disqus username will enable the comment section
  disqus:         qwtel

  # This photo will be used in the about section
  photo:          /public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Matt RUde or [`@mdrude`](https://www.twitter.com/mdrude)

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
