theme: minima
author: "Matt Rude"
title: "Matt Rude's Github Projects"
description: "My collection of published projects"

github_username: mattrude
twitter_username: mdrude

markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

collections:
  posts:
    permalink: /posts/:title
